### ISSUE TITLE
there is a error when i try to convert from bd09ll to wgs84

### ISSUE THREAD

**Issue by zhuang-hao-ming** [fuzhenn/chinese_coordinate_conversion#1]
there is a error when i try to convert from bd09ll to wgs84

```
\node_modules\chncrs\chncrs.js:201
            return GPS[m](parseFloat(c[0]), parseFloat(c[1]));
                         ^

TypeError: GPS[m] is not a function
    at Object.<anonymous> (E:\test\3_22\poi_get\node_modules\chncrs\chncrs.js:201:26)
    at Object._eachCoordinate (E:\test\3_22\poi_get\node_modules\chncrs\chncrs.js:225:23)
    at Object._transformCoordinate (E:\test\3_22\poi_get\node_modules\chncrs\chncrs.js:200:21)
    at Object.transform (E:\test\3_22\poi_get\node_modules\chncrs\chncrs.js:137:25)
    at Object.<anonymous> (E:\test\3_22\poi_get\test.js:3:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```

**Comment by ergoithz** [comment]
For those who are using NPM module, which is outdated and does not support direct wgs84-bd09ll conversions, you can chain both bd09ll-cgj02 and gcj02-wgs84 transforms.
```js
const chncrs = require('chncrs');
chncrs.transform(chncrs.transform([0, 0], 'bd09ll', 'gcj02'), 'gcj02', 'wgs84');
```
